-- Concern Signals: Detected patterns that warrant attention (stress spikes,
-- energy drops, overcommitment, etc.). Generated by comparing snapshots.
-- Part of Memory Upgrade Phase 3.

CREATE TABLE IF NOT EXISTS concern_signals (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  signal_type VARCHAR(30) NOT NULL CHECK (signal_type IN (
    'stress_spike', 'energy_drop', 'isolation', 'overcommitment',
    'stagnation', 'positive_momentum', 'recovery'
  )),
  description TEXT NOT NULL,
  severity VARCHAR(10) NOT NULL DEFAULT 'mild' CHECK (severity IN ('mild', 'moderate', 'significant')),
  snapshot_id UUID REFERENCES state_snapshots(id) ON DELETE SET NULL,
  thread_ids UUID[] DEFAULT '{}',
  acknowledged_at TIMESTAMPTZ,
  resolved_at TIMESTAMPTZ,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_concern_signals_type ON concern_signals (signal_type);
CREATE INDEX IF NOT EXISTS idx_concern_signals_unacknowledged ON concern_signals (created_at DESC)
  WHERE acknowledged_at IS NULL;

COMMENT ON TABLE concern_signals IS 'Detected patterns that warrant attention or care adjustments';
COMMENT ON COLUMN concern_signals.severity IS 'mild (note it), moderate (adjust tone), significant (proactively address)';
